name: CI

on:
  push:
    branches: [master, main]
  pull_request:

permissions:
  contents: read

jobs:
  nix:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - uses: cachix/install-nix-action@630ae543ea3a38a9a4166f03376c02c50f408342 # v31.11.0
      - run: nix flake check 'path:.' --print-build-logs
